/*SQL TRIAL CODE*/

create table DOCTOR(
DOC_LICENSE_NUM  CHAR(7) NOT NULL UNIQUE,
LAST_NAME VARCHAR(20) NOT NULL,
FIRST_NAME VARCHAR(15)  NOT NULL,
ADDRESS VARCHAR(50),
PRIMARY KEY (DOC_LICENSE_NUM)
);

/*SAMPLE DATA*/
INSERT INTO DOCTOR VALUES
('0000001','Smith','John','West Virginia. 26 Santos Street.'),
('0000002','South','Johan','West Virginia. 15 Santos Street.'),
('0000003','Reefs','James','West Virginia. 106 Santos Street.'),
('0000004','Reefs','Jessie','West Virginia. 106 Santos Street.'),
('0000005','Nedd','Milah','Florida, Border Street Avenue, Block 56.'),
('0000006','Colonel','Sanders','Kentucky, Fried Chicken.'),
('0000007','Ricardo','Heart','09 Silver Road, Beckham Park.'),
('0000008','Ketchup','Ash','Pallet Town, West Kanto Region.'),
('0000009','Viva','Giovanni','Soul Silver Street, Viridian City, West Kanto Region.'),
('0000010','Crystal','Grey','City of Evergreen, Central Johto Region.'),
('0000011','Light','Lilian',''),
('0000012','Violet','Vivi','Route 26, Cinnabar Island, Kanto Region.'),
('0000013','Lilam','Loren','Route 205, Floaroma Town, Sinnoh Region.')
;
/*SAMPLE DATA END*/

create table EYEPATIENT(
PAT_ID_NUM VARCHAR(15) NOT NULL UNIQUE,
PHY_LICENSE_NUM CHAR(7) NOT NULL,
STAFF_LICENSE_NUM CHAR(7) NOT NULL,
VA_WITH_SPECT_RIGHT VARCHAR(7) NOT NULL,
VA_WITH_SPECT_LEFT VARCHAR(7) NOT NULL,
VA_NO_SPECT_RIGHT VARCHAR(7) NOT NULL,
VA_NO_SPECT_LEFT VARCHAR(7) NOT NULL,
VISUAL_DISABILITY VARCHAR(15),
DISABILITY_CAUSE VARCHAR(30),
RIGHT_EYE_AFFECTED VARCHAR(12),
LEFT_EYE_AFFECTED VARCHAR(12),
PRIMARY KEY (PAT_ID_NUM),
FOREIGN KEY (PHY_LICENSE_NUM) references DOCTOR(DOC_LICENSE_NUM) on update cascade
);

create table PATIENT(
PAT_ID_NUM VARCHAR(15) NOT NULL UNIQUE,
PAT_LNAME CHAR(7) NOT NULL,
PAT_FNAME CHAR(7) NOT NULL,
PRIMARY KEY (PAT_ID_NUM)
);

create table SURGERY(
CASE_NUM CHAR(10) NOT NULL UNIQUE,
SURG_LICENSE_NUM CHAR(7) NOT NULL,
PAT_ID_NUM VARCHAR(15) NOT NULL,
VISUAL_IMPARITY VARCHAR(100) NOT NULL,
MED_HISTORY VARCHAR(100),
DIAGNOSIS VARCHAR(100),
CLEARANCE_NUM VARCHAR(10) NOT NULL,
SURG_ADDRESS VARCHAR(50),
SURG_DATE DATE NOT NULL,
REMARKS VARCHAR(100),
PRIMARY KEY (CASE_NUM),
FOREIGN KEY (SURG_LICENSE_NUM) REFERENCES DOCTOR(DOC_LICENSE_NUM) on update cascade,
FOREIGN KEY (PAT_ID_NUM) REFERENCES PATIENT(PAT_ID_NUM) on update cascade
);